from typing import Protocol, Optional, List, Dict, Tuple, Set, Any

from core.game_signals import GameSignals
from data.game_state import (
    Scene, Talent, ShootingBloc, MarketGroupState,
    EmailMessage, Tour
)
from data.data_manager import DataManager
from database.db_models import TalentDB, SceneDB
from data.settings_manager import SettingsManager
from ui.theme_manager import ThemeManager, Theme
from services.models.results import TourSponsorshipPreviewResult, ValidationResult
    
class IGameController(Protocol):
    """
    Defines the interface for the GameController that UI components
    and presenters can rely on.
    """

    # --- Properties presenters need ---
    @property
    def tag_definitions(self) -> Dict: ...

    @property
    def market_data(self) -> Dict: ...
    
    @property
    def help_topics(self) -> Dict: ...
    
    @property
    def signals(self) -> GameSignals: ...
    
    @property
    def settings_manager(self) -> SettingsManager: ...

    @property
    def theme_manager(self) -> ThemeManager: ...
    
    @property
    def data_manager(self) -> DataManager: ...

    def get_location_to_region_map(self) -> Dict[str, str]: ...

    # --- UI Data Access ---
    def get_current_theme(self) -> 'Theme': ...
    def get_shot_scenes(self) -> List[Scene]: ...
    def get_all_market_states(self) -> Dict[str, 'MarketGroupState']: ...
    def get_scene_history_for_talent(self, talent_id: int) -> List[Scene]: ...
    def get_talent_by_id(self, talent_id: int) -> Optional[Talent]: ...
    def get_multiple_talents_by_ids(self, talent_ids: List[int]) -> List[Talent]: ...
    def get_talent_chemistry(self, talent_id: int) -> Dict[int, Dict]: ...
    def get_scene_by_id(self, scene_id: int) -> Optional[Scene]: ...
    def get_multiple_scenes_by_ids(self, scene_ids: List[int]) -> List[Scene]: ...
    def get_tour_sponsorship_preview(self, talent_id: int, roles: List[Dict]) -> TourSponsorshipPreviewResult: ...

    # --- Talent Schedule ---
    def get_talent_tours_for_year(self, talent_id: int, year: int) -> List[Tour]: ...

    # --- Talent ---
    def get_castable_scenes(self) -> List[Dict]: ...
    def get_uncast_roles_for_scene(self, scene_id: int) -> List[Dict]: ...
    def get_filtered_talents(self, all_filters: dict) -> List[Talent]: ...
    def cast_talent_for_multiple_roles(self, talent_id: int, hiring_data: Dict): ...
    def get_available_ethnicities(self) -> list[str]: ...
    def get_ethnicity_hierarchy(self) -> Dict[str, List[str]]: ...
    def get_available_nationalities(self) -> List[str]: ...
    def get_locations_by_region(self) -> Dict[str, List[str]]: ...
    def get_talent_schedule_status(self, talent_id: int, year: int): ...
    def get_available_cup_sizes(self) -> list[str]: ...
    def get_talent_go_to_categories(self, talent_id: int) -> List[Dict]: ...
    def add_talents_to_go_to_category(self, talent_ids: list, category_id: int): ...
    def remove_talents_from_go_to_category(self, talent_ids: list, category_id: int): ...

    # --- Go-To List ---
    def get_go_to_list_categories(self) -> List[Dict]: ...
    def get_talents_in_go_to_category(self, category_id: int) -> List[Talent]: ...
    def create_go_to_list_category(self, name: str): ...
    def rename_go_to_list_category(self, category_id: int, new_name: str): ...
    def delete_go_to_list_category(self, category_id: int): ...
    def add_talent_to_go_to_list(self, talent_id: int): ...
    def remove_talents_from_go_to_list(self, talent_ids: list[int]): ...
    def get_go_to_list_talents(self) -> List[Talent]: ...
    def is_talent_in_go_to_list(self, talent_id: int) -> bool: ...

    # --- Hiring ---
    def find_available_roles_for_talent(self, talent_id: int) -> List[Dict]: ...
    def cast_talent_for_virtual_performer(self, talent_id: int, scene_id: int, virtual_performer_id: int, cost: int): ...
    def get_eligible_talent_for_role(self, scene_id: int, vp_id: int, filters: dict = None) -> List[TalentDB]: ...
    def get_role_details_for_ui(self, scene_id: int, vp_id: int) -> Dict: ...
    def calculate_total_demand(self, talent_id: int, scene_id: int, vp_id: int) -> Dict[str, int]: ...
    def calculate_demands_for_multiple_talents(self, talent_ids: List[int], scene_id: int, vp_id: int) -> Dict[int, int]: ...
    def sponsor_tour(self, talent_id: int, roles_to_cast: list, tour_details: dict, total_upfront_cost: int): ...
    def get_effective_locations_for_multiple_talents(self, talent_ids: List[int], absolute_week: int) -> Dict[int, str]: ...
    def calculate_bulk_hiring_costs(self, talent_id: int, roles: List[Dict]) -> Optional[Dict]: ...
    def validate_potential_bookings(self, talent_id: int, roles_data: List[Dict]) -> Dict[Tuple[int, int], ValidationResult]: ...
    def calculate_contract_salary(self, talent_id: int, terms: Dict) -> int: ...
    def sign_contract(self, talent_id: int, terms: Dict): ...
    def get_unique_contract_options(self) -> Tuple[List[str], List[str]]: ...

    # --- Scene Planner ---
    def create_shooting_bloc(self, scheduled_absolute_week: int, num_scenes: int, name: str, logistics: Dict, budget_data: Dict, policies: List[str]) -> bool: ...
    def calculate_shooting_bloc_cost(self, location_id: str, department_budgets: Dict[str, int], crew_assignments: Dict[str, Dict[str, Any]], picture_set_settings: Dict[str, Any], policies: List[str]) -> int: ...
    def get_blocs_for_schedule_view(self, year: int) -> List[ShootingBloc]: ...
    def update_scene_full(self, scene_data: Scene) -> Dict: ...
    def get_bloc_by_id(self, bloc_id: int) -> Optional[ShootingBloc]: ...
    def get_thematic_tags_for_planner(self) -> Tuple[List[Dict], Set[str], Set[str]]: ...
    def get_physical_tags_for_planner(self) -> Tuple[List[Dict], Set[str], Set[str]]: ...
    def get_action_tags_for_planner(self) -> Tuple[List[Dict], Set[str], Set[str]]: ...
    def get_favorite_tags(self, tag_type: str) -> List[str]: ...
    def toggle_favorite_tag(self, tag_name: str, tag_type: str): ...
    def reset_favorite_tags(self, tag_type: str): ...
    def is_performer_eligible_for_tag(self, performer, tag_name: str) -> bool: ...
    def delete_scene(self, scene_id: int, silent: bool = False, penalty_percentage: float = 0.0): ...

    # --- Shooting & Release ---
    def resolve_interactive_event(self, event_id: str, scene_id: int, talent_id: int, choice_id: str) -> None: ...
    def discover_and_create_chemistry_from_cast(self, cast_talents: List[Talent]): ...
    def release_scene(self, scene_id: int): ...
    def start_editing_scene(self, scene_id: int, editing_tier_id: str): ...
    def get_resolved_group_data(self, group_name: str) -> Dict: ...
    
    # --- Email ---
    def get_all_emails(self) -> List['EmailMessage']: ...
    def get_unread_email_count(self) -> int: ...
    def mark_email_as_read(self, email_id: int): ...
    def delete_emails(self, email_ids: list[int]): ...

    # --- Core Game Loop ---
    def advance_week(self): ...

    # --- Session Management ---
    def new_game_started(self): ...
    def load_game(self, save_name: str): ...
    def save_game(self, save_name: str): ...
    def delete_save_file(self, save_name: str) -> bool: ...
    def continue_game(self): ...
    def quick_save(self): ...
    def quick_load(self): ...
    def return_to_main_menu(self, exit_save: bool): ...
    def quit_game(self, exit_save: bool = False): ...
    def handle_application_shutdown(self): ...
    def handle_game_over(self): ...
    def check_for_saves(self) -> bool: ...