from typing import Protocol, Optional, List, Dict, Tuple, Set

from core.game_signals import GameSignals
from data.game_state import (
    Scene, Talent, ShootingBloc, MarketGroupState,
    EmailMessage
)
from services.query.talent_query_service import TalentQueryService
from data.data_manager import DataManager
from data.settings_manager import SettingsManager
from ui.theme_manager import ThemeManager, Theme
    
class IGameController(Protocol):
    """
    Defines the interface for the GameController that UI components
    and presenters can rely on.
    """

    # --- Properties presenters need ---
    @property
    def talent_query_service(self) -> TalentQueryService: ...

    @property
    def tag_definitions(self) -> Dict: ...

    @property
    def market_data(self) -> Dict: ...
    
    @property
    def help_topics(self) -> Dict: ...
    
    @property
    def signals(self) -> GameSignals: ...
    
    @property
    def settings_manager(self) -> SettingsManager: ...

    @property
    def theme_manager(self) -> ThemeManager: ...
    
    @property
    def data_manager(self) -> DataManager: ...

    # --- UI Data Access ---
    def get_current_theme(self) -> 'Theme': ...
    def get_shot_scenes(self) -> List[Scene]: ...
    def get_all_market_states(self) -> Dict[str, 'MarketGroupState']: ...
    def get_scene_history_for_talent(self, talent_id: int) -> List[Scene]: ...
    def get_talent_by_id(self, talent_id: int) -> Optional[Talent]: ...
    def get_talent_chemistry(self, talent_id: int) -> Dict[int, Dict]: ...
    
    # --- Methods for ScenePlannerPresenter ---
    def get_scene_for_planner(self, scene_id: int) -> Optional[Scene]: ...
    def update_scene_full(self, scene_data: Scene) -> Dict: ...
    def get_bloc_by_id(self, bloc_id: int) -> Optional[ShootingBloc]: ...
    def get_thematic_tags_for_planner(self) -> Tuple[List[Dict], Set[str], Set[str]]: ...
    def get_physical_tags_for_planner(self) -> Tuple[List[Dict], Set[str], Set[str]]: ...
    def get_action_tags_for_planner(self) -> Tuple[List[Dict], Set[str], Set[str]]: ...
    def get_favorite_tags(self, tag_type: str) -> List[str]: ...
    def toggle_favorite_tag(self, tag_name: str, tag_type: str): ...
    def delete_scene(self, scene_id: int, silent: bool = False, penalty_percentage: float = 0.0): ...

    # --- Methods for HireTalentPresenter ---
    def get_castable_scenes(self) -> List[Dict]: ...
    def get_uncast_roles_for_scene(self, scene_id: int) -> List[Dict]: ...
    def get_filtered_talents(self, all_filters: dict) -> List[Talent]: ...
    def cast_talent_for_multiple_roles(self, talent_id: int, roles: list): ...
    def get_available_ethnicities(self) -> list[str]: ...
    def get_available_boob_cups(self) -> list[str]: ...
    def get_talent_go_to_categories(self, talent_id: int) -> List[Dict]: ...
    def add_talents_to_go_to_category(self, talent_ids: list, category_id: int): ...
    def remove_talents_from_go_to_category(self, talent_ids: list, category_id: int): ...

    # --- Methods for GoToTalentDialog ---
    def get_go_to_list_categories(self) -> List[Dict]: ...
    def get_talents_in_go_to_category(self, category_id: int) -> List[Talent]: ...
    def create_go_to_list_category(self, name: str): ...
    def rename_go_to_list_category(self, category_id: int, new_name: str): ...
    def delete_go_to_list_category(self, category_id: int): ...
    def add_talents_to_go_to_category(self, talent_ids: list[int], category_id: int): ...
    def remove_talents_from_go_to_category(self, talent_ids: list[int], category_id: int): ...
    def add_talent_to_go_to_list(self, talent_id: int): ...
    def remove_talents_from_go_to_list(self, talent_ids: list[int]): ...

    # --- Email Methods ---
    def get_all_emails(self) -> List['EmailMessage']: ...
    def get_unread_email_count(self) -> int: ...
    def mark_email_as_read(self, email_id: int): ...
    def delete_emails(self, email_ids: list[int]): ...

    # --- Core Game Loop and Actions ---
    def advance_week(self): ...
    def release_scene(self, scene_id: int): ...
    def start_editing_scene(self, scene_id: int, editing_tier_id: str): ...
    def create_shooting_bloc(self, week: int, year: int, num_scenes: int, settings: Dict[str, str], name: str, policies: List[str]) -> bool: ...
    def create_blank_scene(self, week: Optional[int] = None, year: Optional[int] = None) -> int: ...
    def calculate_talent_demand(self, talent_id: int, scene_id: int, vp_id: int) -> int: ...
    def cast_talent_for_virtual_performer(self, talent_id: int, scene_id: int, virtual_performer_id: int, cost: int): ...
    def resolve_interactive_event(self, event_id: str, scene_id: int, talent_id: int, choice_id: str) -> None: ...
    def discover_and_create_chemistry_from_cast(self, cast_talents: List[Talent]): ...

    # --- Session Management ---
    def new_game_started(self): ...
    def load_game(self, save_name: str): ...
    def save_game(self, save_name: str): ...
    def delete_save_file(self, save_name: str) -> bool: ...
    def continue_game(self): ...
    def quick_save(self): ...
    def quick_load(self): ...
    def return_to_main_menu(self, exit_save: bool): ...
    def quit_game(self, exit_save: bool = False): ...
    def handle_application_shutdown(self): ...
    def handle_game_over(self): ...
    def check_for_saves(self) -> bool: ...

    # --- Miscellaneous ---
    def get_resolved_group_data(self, group_name: str) -> Dict: ...